"""Add recipes cache table

Revision ID: 04c1428fc12a
Revises: ff1d46fec4c6
Create Date: 2026-07-18 00:05:20.691894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c1428fc12a'
down_revision = 'ff1d46fec4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('ready_minutes', sa.Integer(), nullable=True),
    sa.Column('prep_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_minutes', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
